import json, collections
S='/private/tmp/claude-501/-Users-Shared-Github-snagr-mintlify-kb/fe520fb6-31b2-4c07-aef5-c39f0f600c2f/scratchpad'
r=json.load(open(f'{S}/report.json')); pn=json.load(open(f'{S}/private_nav.json')); media=json.load(open(f'{S}/media_map.json'))
L=["# Helpjuice to Mintlify migration report\n\nGenerated 2026-09-22 from the `snagr-*-2026-09-22.csv` export.\n","## Summary\n","| Item | Count |\n|---|---|"]
per=collections.Counter(v['lang'] for v in r['pages'].values())
L.append(f"| Published articles migrated | {len(r['pages'])} |")
for k,v in per.items(): L.append(f"| &nbsp;&nbsp;{k} | {v} |")
L.append(f"| Unpublished articles skipped | {len(r['unpublished'])} |")
L.append(f"| Curated overview pages created | {len(r['curated_pages'])} |")
L.append(f"| Images downloaded | {sum(1 for m in media if m.get('status')=='ok')} |")
L.append(f"| Image downloads refused (HTTP 403) | {sum(1 for m in media if str(m.get('status','')).startswith('fail'))} |")
L.append(f"| Dead legacy image links (support.snagr.co.uk) | {sum(1 for m in media if m['kind']=='dead-confluence')} unique URLs, {sum(len(v) for v in r['missing_images'].values())} references on {len(r['missing_images'])} pages |")
L.append(f"| Embedded videos kept (Vimeo/YouTube iframes) | {sum(1 for m in media if m['kind']=='video')} |")
L.append(f"| Dead internal links removed (text kept) | {sum(r['unresolved_links'].values())} |\n")
L.append("## How the mapping was rebuilt\n\nThe questions export has an empty `category_id` column, so article placement was recovered by crawling the live site (`snagr.helpjuice.com`): every `/_questions/<id>` page carries `category-id` and `current-language` meta tags. Article order inside a category follows the order shown on the Helpjuice category pages where available, otherwise creation date.\n")
L.append("## Login-only sections (not published)\n\nThese articles live in categories that require a Helpjuice login, so the crawl could not confirm their category. They were placed by title and are generated under `en/aahk-trd/`, `en/aahk-cwd/` and `en/power-bi-integration/`, which `.mintignore` excludes from the build. To publish them, remove those lines from `.mintignore` and add the groups below to the `en` entry in `docs.json`.\n")
for qid,title,path in r['private_placed']: L.append(f"- {title} -> {path}")
L.append("\n```json\n"+json.dumps(pn, indent=2, ensure_ascii=False)+"\n```\n")
L.append("## Skipped articles\n\n- Snagr ltd Glossary (614229): the export only contains an empty glossary widget, no terms.\n\nUnpublished on Helpjuice (not migrated):\n")
for qid,t in r['unpublished']: L.append(f"- {t} ({qid})")
L.append("\n## Missing images\n\nOld articles embedded images from the retired Confluence site `support.snagr.co.uk` (offline, not in the Wayback Machine). Those image tags were removed and each affected page starts with a `{/* TODO ... */}` comment. Pages affected:\n")
for path,urls in sorted(r['missing_images'].items()): L.append(f"- `{path}` ({len(urls)} images)")
fails=[m for m in media if str(m.get('status','')).startswith('fail')]
if fails:
    L.append("\nRefused downloads:\n")
    for m in fails: L.append(f"- {m['url']} ({m['status']}) used on question(s) {', '.join(m['questions'])}")
L.append("\n## Dead internal links\n\nThese hrefs pointed to deleted or unpublished Helpjuice articles (they 404 on the live site too). The link was dropped and the link text kept.\n")
for h,c in sorted(r['unresolved_links'].items(), key=lambda kv:-kv[1]): L.append(f"- `{h}` ({c}x)")
L.append("\n## Curated overview pages\n\nHelpjuice starter-guide categories had no articles of their own but listed links to articles elsewhere. Those became `index.mdx` pages with the same link list.\n")
for path,name,n in r['curated_pages']: L.append(f"- `{path}` - {name} ({n} links)")
L.append("\n## Duplicate slugs\n\nTwo articles in the same folder had the same Helpjuice codename; the second one got a `-2` suffix.\n")
for qid,t,path in r['dup_slugs']: L.append(f"- {t} -> `{path}-2`")
L.append("\n## Things to review by hand\n\n- Branding: `docs.json` still uses the starter logo files in `logo/` and `favicon.svg`; replace them with SnagR assets. The navbar links, footer socials and starter pages were removed.\n- Colours: primary `#086F92` was derived from the old Helpjuice theme (`#09b2e6` failed the WCAG contrast check).\n- Chinese article URLs: Helpjuice used numeric codenames for most Chinese articles, so their file names are the Helpjuice question ids (for example `zh-hant/issues/add-issues/280009.mdx`). Rename them if you want readable URLs; nothing links to the old codenames.\n- Group names in the sidebar keep the original Helpjuice category names, including capitalisation and the typo in \"Troubelshooting for Admins\".\n- Guidde walkthroughs were flattened to their screenshots and step text.\n- Some tiny icon images (device/website markers) use their file name as alt text.\n")
open('/Users/Shared/Github/snagr-mintlify-kb/helpjuice-export/migration-report.md','w').write('\n'.join(L)+'\n')
print("report written")
